name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5'
      - name: Install ocamlformat
        run: opam install ocamlformat.$(awk -F= '/^version/ {print $2}' .ocamlformat)
      - name: Check formatting
        run: opam exec -- dune build @fmt

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {ocaml-compiler: '4.14', os: ubuntu-latest}
          - {ocaml-compiler: '5.1', os: ubuntu-latest}
          - {ocaml-compiler: '5.2', os: ubuntu-latest}
          - {ocaml-compiler: '5.2', os: windows-latest}
    steps:
      - uses: actions/checkout@v7
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install dependencies
        run: opam install --deps-only --with-test .
      - name: Build
        run: opam exec -- dune build
      - name: Test
        run: opam exec -- dune build @github_action_tests

  nix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {ocamlVersion: 4_14, os: ubuntu-latest}
          - {ocamlVersion: 5_1, os: ubuntu-latest}
          - {ocamlVersion: 5_2, os: ubuntu-latest}
          - {ocamlVersion: 5_2, os: macos-latest}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://anmonteiro.nix-cache.workers.dev
            extra-trusted-public-keys = ocaml.nix-cache.com-1:/xI2h2+56rwFfKyyFVbkJSeGqSIYMC/Je+7XXqGKDIY=
      - name: Run nix-build
        run: nix-build ./nix/ci/test.nix --argstr ocamlVersion ${{ matrix.ocamlVersion }}
