name: Build doc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5'
      - name: Install dependencies
        run: opam install --deps-only --with-doc .
      - name: Build doc
        run: opam exec -- dune build @doc
      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _build/default/_doc/_html
